- name: mysql 
  hosts: mysql
  become: yes
  vars:
    mysql_root_password:  "ExpenseApp@1"
  tasks:
    # - name: Install python mysql dependency
    #   ansible.builtin.dnf:
    #     name: python3-PyMySQL
    #     state: present

    - name: Disable default mysql module
      ansible.builtin.command: dnf module disable mysql -y

    - name: Install MySQL repo
      ansible.builtin.dnf:
        name: https://dev.mysql.com/get/mysql80-community-release-el7.rpm
        state: present

    - name: Install MySQL server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present
    
    - name: start the service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: set mysql password
      community.mysql.mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        check_implicit_admin: true
        state: present
      no_log: true

