- name: mysql 
  hosts: mysql
  become: yes
  tasks:
      - name: Install MySQL server
        ansible.builtin.package:
          name: mysql-server
          state: present
    
      - name: Start and enable mysqld service
        ansible.builtin.service:
          name: mysqld
          state: started
          enabled: yes

      - name: Install PyMySQL
        ansible.builtin.dnf:
          name: python3-PyMySQL
          state: present

      - name: Set root password
        community.mysql.mysql_user:
          name: root
          host: localhost
          password: "ExpenseApp@1"
          check_implicit_admin: true
          login_unix_socket: /var/lib/mysql/mysql.sock
      


